@echo off
setlocal EnableExtensions EnableDelayedExpansion

rem ============================================================
rem  OpenWorktree one-click launcher (distribution build)
rem  First run generates config\gate.toml and the data\ folder,
rem  then starts the backend and opens the browser.
rem  All runtime data stays inside the local data\ folder.
rem  (Console messages are English-only on purpose: cmd.exe batch
rem   parsing of non-ASCII text is codepage-fragile.)
rem ============================================================

set "ROOT=%~dp0"
set "CONFIG=%ROOT%config\gate.toml"
set "PORT=18080"
set "URL=http://127.0.0.1:%PORT%/"

rem ---------- 1. Check Java ----------
set "JAVA_EXE="
if exist "%JAVA_HOME%\bin\java.exe" set "JAVA_EXE=%JAVA_HOME%\bin\java.exe"
if not defined JAVA_EXE (
    for /f "delims=" %%J in ('where java.exe 2^>nul') do if not defined JAVA_EXE set "JAVA_EXE=%%J"
)
if not defined JAVA_EXE (
    echo [ERROR] Java not found. Please install Java 17+ and add it to PATH or set JAVA_HOME.
    pause
    exit /b 1
)

rem ---------- 2. First run: generate portable config ----------
if exist "%CONFIG%" goto :config_ready

echo [INFO] First run: generating config\gate.toml ...
if not exist "%ROOT%config" mkdir "%ROOT%config"
if not exist "%ROOT%data" mkdir "%ROOT%data"
set "R=%ROOT:\=/%"

> "%CONFIG%" echo # OpenWorktree runtime config (generated by start_web_windows.bat; edit port below on conflict)
>> "%CONFIG%" echo schema_version = 2
>> "%CONFIG%" echo project = "openworktree"
>> "%CONFIG%" echo auth_repo = "%R%data/auth.git"
>> "%CONFIG%" echo clones_root = "%R%data/clones"
>> "%CONFIG%" echo target_ref_whitelist = ["refs/heads/main"]
>> "%CONFIG%" echo gate_home = "%R%data/gate-home"
>> "%CONFIG%" echo approvals_dir = "%R%data/gate-home/approvals"
>> "%CONFIG%" echo db_path = "%R%data/gate-home/gate.db"
>> "%CONFIG%" echo blob_root = "%R%data/gate-home/blobs"
>> "%CONFIG%" echo audit_path = "%R%data/gate-home/audit.jsonl"
>> "%CONFIG%" echo locks_dir = "%R%data/gate-home/locks"
>> "%CONFIG%" echo index_dir = "%R%data/gate-home/idx"
>> "%CONFIG%" echo.
>> "%CONFIG%" echo [gate_identity]
>> "%CONFIG%" echo name = "openworktree"
>> "%CONFIG%" echo email = "openworktree@localhost"
>> "%CONFIG%" echo date = "1700000000 +0000"
>> "%CONFIG%" echo.
>> "%CONFIG%" echo [web]
>> "%CONFIG%" echo bind = "127.0.0.1"
>> "%CONFIG%" echo port = %PORT%
>> "%CONFIG%" echo allowed_origins = ["127.0.0.1", "localhost"]
>> "%CONFIG%" echo human_token_file = "%R%data/gate-home/web-token"
>> "%CONFIG%" echo.
>> "%CONFIG%" echo [session]
>> "%CONFIG%" echo port_range_min = 49152
>> "%CONFIG%" echo port_range_max = 61000
>> "%CONFIG%" echo default_cli = "claude"
>> "%CONFIG%" echo start_timeout_seconds = 60
>> "%CONFIG%" echo.
>> "%CONFIG%" echo # Review engine is optional; configure it later in Settings inside the app.
>> "%CONFIG%" echo # [engine]
>> "%CONFIG%" echo # cmd = "C:/path/to/engine.exe"
>> "%CONFIG%" echo # timeout_seconds = 600

:config_ready

rem ---------- 3. Port pre-check: busy means an instance is likely already running ----------
powershell -NoProfile -Command "try { $client = New-Object System.Net.Sockets.TcpClient; $client.Connect('127.0.0.1',%PORT%); $client.Close(); exit 0 } catch { exit 1 }" >nul 2>nul
if not errorlevel 1 (
    echo [HINT] Port %PORT% is already in use. If this is a running OpenWorktree, just use the browser.
    echo [HINT] Otherwise edit "port" under [web] in config\gate.toml and run this script again.
    start "" "%URL%"
    timeout /t 5 /nobreak >nul
    exit /b 0
)

rem ---------- 4. Start backend (separate window, errors stay visible) ----------
echo [INFO] Starting OpenWorktree backend on 127.0.0.1:%PORT% ...
start "OpenWorktree" /D "%ROOT%" cmd /k ""%JAVA_EXE%" -Dfile.encoding=UTF-8 -cp "%ROOT%ui;%ROOT%lib\*" gate.web.GateWebApp --config "%CONFIG%""

rem ---------- 5. Wait for the port, then open the browser ----------
set "READY=0"
for /l %%I in (1,1,15) do (
    powershell -NoProfile -Command "try { $client = New-Object System.Net.Sockets.TcpClient; $client.Connect('127.0.0.1',%PORT%); $client.Close(); exit 0 } catch { exit 1 }" >nul 2>nul
    if not errorlevel 1 (
        set "READY=1"
        goto :ready
    )
    timeout /t 1 /nobreak >nul
)

:ready
if "%READY%"=="0" (
    echo [ERROR] Service did not start on %URL%. Read the error in the "OpenWorktree" window.
    echo [HINT] Common causes: port already taken - edit config\gate.toml - or Java older than 17.
    pause
    exit /b 1
)

echo [INFO] Opening %URL% ...
start "" "%URL%"
echo.
echo [INFO] Login token: see data\gate-home\web-token, or the GATE_WEB_TOKEN=... line
echo        printed in the "OpenWorktree" window. Paste it on the login page.
echo [INFO] All data (db/clones/audit) stays inside the local data\ folder.
timeout /t 5 /nobreak >nul
exit /b 0
