package gate.ports;

import java.util.List;

/**
 * Startup preflight (架构落地执行文档 §10.3). Fail-closed: any failing check refuses to proceed
 * with exit 22.
 *
 * <p>Two tiers, per the P1 ruling:
 * <ul>
 *   <li><b>core</b> — always enforced in P1: {@code auth.git} is bare; hook present, executable and
 *       byte-identical to the generated bytes; {@code core.hooksPath} unset;
 *       {@code receive.advertisePushOptions=true}; {@code receive.denyDeletes=true};
 *       {@code receive.denyNonFastForwards=true}; approvals dir + {@code consumed/} writable;
 *       HEAD symbolic-ref points at the target branch; no clone is a linked worktree or uses
 *       {@code alternates} into {@code auth.git}; hook forward self-check.</li>
 *   <li><b>engine</b> — only when an engine is configured (P2): {@code --version} parses,
 *       {@code review commit --help} exposes the required flags (N4), provider reachable.</li>
 * </ul>
 *
 * <p>The hook self-check runs in a throwaway sandbox bare repo built by the <em>same</em> generator
 * and the <em>same</em> writer, pushing a happy path (expect ACCEPT) and a no-token push (expect
 * REJECT), then compares sha256 with the real hook. It never pushes to the real target branch:
 * doing so would add a self-check commit to authoritative history that {@code denyDeletes} +
 * {@code denyNonFastForwards} make unremovable. This exists because a broken hook and a healthy
 * hook look identical from outside — both reject everything (spike-结论 §2.4).
 */
public interface PreflightChecker {

    Report check();

    record Report(List<Check> checks) {

        public Report {
            checks = List.copyOf(checks);
        }

        public boolean ok() {
            return checks.stream().allMatch(Check::passed);
        }

        public List<Check> failures() {
            return checks.stream().filter(c -> !c.passed()).toList();
        }
    }

    record Check(String id, boolean passed, String detail, Tier tier) {

        public static Check pass(String id, String detail, Tier tier) {
            return new Check(id, true, detail, tier);
        }

        public static Check fail(String id, String detail, Tier tier) {
            return new Check(id, false, detail, tier);
        }
    }

    enum Tier {
        CORE,
        ENGINE
    }
}
